[tasks.testWin]
run_windows = "git pull && flutter run -d windows"

[tasks.devSite]
dir = "site"
run = "npm run dev"

[tasks.deploySite]
dir = "site"
run = "npm run deploy"

[tools]
flutter = "beta"
node = "latest"
wrangler = "latest"
