name: zup
description: "Zup is a desktop updater for applications distributed as ZIP assets on GitHub Releases."
publish_to: "none"

version: 0.0.2

environment:
  sdk: ^3.11.0-200.1.beta

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  archive: ^4.0.7
  cupertino_icons: ^1.0.8
  file_selector: ^1.0.3
  google_fonts: ^8.0.2
  http: ^1.5.0
  intl: ^0.20.2
  path: ^1.9.1
  path_provider: ^2.1.5
  sqflite_common_ffi: ^2.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  generate: true
  uses-material-design: true
